name: Check Unique UUIDs in YAML files

on:
  pull_request:
    paths:
      - 'data/**/*.yaml'
  workflow_dispatch:

jobs:
  check-uuids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run duplicate UUID check
        run: python .github/workflows/scripts/check_uuids.py data