name: Validate Content

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "7.0" ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: |
          python -m pip install pyyaml

      - name: Validate Quiz Content
        run: python .github/workflows/scripts/validate_quiz.py data